# Generated by Django 3.1.4 on 2020-12-05 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201205_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='department',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='api.department'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='faculty',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='api.faculty'),
        ),
    ]
