# Generated by Django 3.1.4 on 2020-12-05 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201205_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.department'),
        ),
        migrations.AlterField(
            model_name='event',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.faculty'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='api.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examination',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='api.faculty'),
            preserve_default=False,
        ),
    ]
