# Generated by Django 3.1.4 on 2020-12-05 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201205_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('Sessional', 'Sessional'), ('Mid-Sem', 'Mid-Sem'), ('Practical', 'Practical'), ('End-Sem', 'End-Sem')], max_length=100),
        ),
        migrations.AddField(
            model_name='examination',
            name='semester',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
