# Generated by Django 3.1.4 on 2020-12-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201205_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='title',
        ),
        migrations.AddField(
            model_name='examination',
            name='detail',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
