# Generated by Django 3.1.4 on 2020-12-12 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_holiday_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['day', 'month']},
        ),
    ]
