# Generated by Django 3.1.4 on 2020-12-12 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20201212_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entranceexamination',
            options={'ordering': ['year', 'day', 'month']},
        ),
    ]
