# Generated by Django 3.1.4 on 2020-12-12 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20201212_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entranceexamination',
            options={'ordering': ['year', 'month', 'day']},
        ),
    ]
