# Generated by Django 3.1.4 on 2020-12-12 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20201212_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['year', 'month', 'day']},
        ),
    ]
